#!/bin/bash

# Script to automate multiple tracmass runs
# Based on script by Ashley Van Name

# ===================USER INPUT=====================#

infil=/Users/liz/TOOLS/tracmass/projects/pipa/template.in
tempfil=$infil.tmp
outfil=/Users/liz/TOOLS/tracmass/projects/pipa/pipa.in
yr=1993
nmdays=(31 28 31 30 31 30 31 31 30 31 30 31)

while (($yr <= 2012)); do

      if (($yr == 1992)); then
         mon=6;
      else
         mon=11;
      fi              

      ineq=$((yr%4))
      if (($ineq == 0)); then
         nmdays[1]=29
      else
         nmdays[1]=28
      fi

      while (($mon <= 12)); do
            day=13
            
            if (($yr == 2013 && $mon == 12)); then
               nmdays[11]=24
            else
               nmdays[11]=31
            fi

            while (($day <= ${nmdays[$((mon-1))]})); do   
                  # Edit pipa.in file
                  cp $infil $infil.tmp

                  sed -i -n "s/<DAY>/$day/g"   $tempfil
                  sed -i -n "s/<MONTH>/$mon/g" $tempfil
                  sed -i -n "s/<YEAR>/$yr/g"   $tempfil 

                  mv $tempfil $outfil

                  # Run TRACMASS
                  ./runtrm
                  ((day+=1))
            done 
            ((mon+=1))
      done
      ((yr+=1))
rm $infil.tmp*
done

