#!/bin/bash

# Script to automate multiple tracmass runs
# Based on script by Ashley Van Name

# ===================USER INPUT=====================#

infil=/Users/liz/TOOLS/tracmass/projects/maphil/forward_template.in
tempfil=$infil.tmp
outfil=/Users/liz/TOOLS/tracmass/projects/maphil/maphil.in
yr=2010
nmdays=(31 28 31 30 31 30 31 31 30 31 30 31)

intrun=9
nff=1
isec=4
partquant=100


while (($yr <= 2013)); do
echo $yr
      #if (($yr == 2010)); then
      #   mon=12;
      #else
      mon=1;
      #fi              

      ineq=$((yr%4))
      if (($ineq == 0)); then
         nmdays[1]=29
      else
         nmdays[1]=28
      fi

      while (($mon <= 5)) || (($mon == 12)); do
            day=1
            echo ${nmdays[$mon-1]}
            while (($day <= ${nmdays[$mon-1]})); do   
 
                 # Edit pipa.in file
                  cp $infil $infil.tmp
  
#                  sed -i -n "s/<OUTDIR>/$outdatadir/g" $tempfil
                  sed -i -n "s/<DAY>/$day/g"           $tempfil
                  sed -i -n "s/<MONTH>/$mon/g"         $tempfil
                  sed -i -n "s/<YEAR>/$yr/g"           $tempfil 
                  sed -i -n "s/<RUN>/$intrun/g"        $tempfil
                  sed -i -n "s/<NFF>/$nff/g"           $tempfil
                  sed -i -n "s/<ISEC>/$isec/g"         $tempfil
                  sed -i -n "s/<NPART>/$partquant/g"   $tempfil

                  mv $tempfil $outfil

                  # Run TRACMASS
                  ./runtrm_maphil
                  ((day+=1))
            done
            ((mon+=1))
            if (($mon == 6)); then
               mon=12
            fi
      done
      ((yr+=1))
rm $infil.tmp*
done

