PROJECT	          = arctic
CASE              = arctic
RUNFILE 	  = runtrm

#F95COMPILER      = "g95"
F95COMPILER       = "gfortran"
#F95COMPILER      = "ifort"

#NETCDFLIBS	  = "none"
#NETCDFLIBS       = "automatic"
NETCDFLIBS        = "macports"
#NETCDFLIBS       = "fink"
#NETCDFLIBS       = "source"

#================================================================

include Makefile.global

