PROJECT	          = vip
CASE              = vip
RUNFILE 	  = runtrm_$(PROJECT)

#F95COMPILER        = "g95"
F95COMPILER        = "gfortran"
#F95COMPILER        = "ifort"
#FF                 = "/sw/bin/gfortran-fsf-4.9" #Alt. compiler location

#NETCDFLIBS	       = "none"
#NETCDFLIBS        = "automatic"
NETCDFLIBS        = "macports"
#NETCDFLIBS        = "fink"
#NETCDFLIBS        = "source"

#================================================================

include Makefile.global

