#!/bin/bash

make clean
make

declare -a time

time=( 236 238 ) # 60000 cutoff 2-6 days 2006






timelength=${#time[@]}
date > log
for ((i=0;i<$timelength;i=i+2)); 
  do
  jd1=${time[${i}]}
  jd2=${time[${i}+1]}
  table="sens100vel"$jd1"B"

  CT1="CREATE TABLE IF NOT EXISTS traj."$table"run  "
  CT2="(ints INT , ntrac INT, x1 REAL, y1 REAL, z1 REAL, " 
  CT3=" ijk  REAL, INDEX(ints), INDEX(ntrac), INDEX(ijk) );"
  CT="$CT1 $CT2 $CT3"
  TR="TRUNCATE traj."$table"run;" 
  
  #CT1="CREATE TABLE IF NOT EXISTS traj."$table"run  "
  #CT2="(ints INT,ntrac INT,n REAL,x1 REAL,y1 REAL,z1 REAL,tt " 
  #CT3=" REAL,t0 REAL,subvol REAL,temp REAL,salt REAL,dens "
  #CT4=" REAL,arct REAL, ijk REAL, INDEX(ints), INDEX(ntrac), INDEX(ijk) );"
  #CT="$CT1 $CT2 $CT3 $CT4"
  #TR="TRUNCATE traj."$table"run;" 
  
  /usr/local/mysql/bin/mysql -D traj -u root -e "$CT"
  /usr/local/mysql/bin/mysql -D traj -u root -e "$TR"

  ./runtraj $jd1 $jd2 $table
  echo $jd1 >> log
  date >> log
done
