#!/bin/bash

make clean
make

time=( 0236 0238 ) # 60000 cutoff 2-6 days 2006
jd1=${time[${i}]}
jd2=${time[${i}+1]}
table="rivmixKenn"$jd1"B"

CT1="CREATE TABLE IF NOT EXISTS traj."$table"run  "
CT2="(ints INT , ntrac INT, x1 REAL, y1 REAL, z1 REAL, " 
CT3=" ijk  REAL, INDEX(ints), INDEX(ntrac), INDEX(ijk) );"
CT="$CT1 $CT2 $CT3"
TR="TRUNCATE traj."$table"run;" 
  
/usr/local/mysql/bin/mysql -D traj -u root -e "$CT"
/usr/local/mysql/bin/mysql -D traj -u root -e "$TR"

./runtraj $jd1 $jd2 $table

