#!/bin/bash

make clean
make

time="387 391 398 410 417 424 430 435 439 446 451 467 496 597 600 611 636 677 684 691"

for x in $time
  do
  table="r"$x"B"
  CT1="CREATE TABLE IF NOT EXISTS traj."$table"run  "
  CT2="(ints INT,ntrac INT,n REAL,x1 REAL,y1 REAL,z1 REAL,tt " 
  CT3=" REAL,t0 REAL,subvol REAL,temp REAL,salt REAL,dens "
  CT4=" REAL,arct REAL, ijk REAL, INDEX(ints), INDEX(ntrac), INDEX(ijk) );"
  CT="$CT1 $CT2 $CT3 $CT4"

  TR="TRUNCATE traj."$table"run;" 
  
  /usr/local/mysql/bin/mysql -D traj -u root -e "$CT"
  /usr/local/mysql/bin/mysql -D traj -u root -e "$TR"

  ./runtraj $x $table".01"
done


